### ISSUE TITLE
Adding a LICENSE file.

### ISSUE THREAD

**Issue by VannTen** [michaelb/vim-tips#20]
Would you mind adding an explicit License file (or other indication) ?
I was in the process of making a PKGBUILD and wondering was to indicate for it.

Thanks :)

**Comment by michaelb** [comment]
Oversight from me, MIT added :-)

I feel strange that this old project is still used and _packaged_ lol. I guess it just continues working ?

**Comment by VannTen** [comment]
Well, I just package because I tend to prefer have vim-plugins
system wide rather than at the user level. And it's dead-easy for vim
plugins so...

It works for me at least ;)

Could you issue a new tag/release now that the license is part of the
source ? Since with MIT we need to include the license itself to retain
the assignation.

(no worries if not, I'll make a package from master instead)

**Comment by michaelb** [comment]
done :-)

**Comment by VannTen** [comment]
I think you missed some stuff, your v0.4 tags a commits from last year ^
(Sorry to keep bothering : ( )

**Comment by michaelb** [comment]
Please keep complaining at my thoughtlessness😅

**Comment by michaelb** [comment]
Republished a v0.4 tag this time including the licence (which I had created via the github interface and forgot to pull when creating the tag)

**Comment by VannTen** [comment]
https://aur.archlinux.org/packages/vim-tips
Just pushed the aur package :+1: 
Thanks !
